Controllers/OrderDetailController.cs
using Microsoft.AspNetCore.Mvc;
using StaticCRUD.Models;
using System.Data.SqlClient;
using System.Data;

namespace StaticCRUD.Controllers
{
    [CheckAccess]
    public class OrderDetailController : Controller
    {
        private IConfiguration _configuration;
        public OrderDetailController(IConfiguration configuration)
        {
            _configuration = configuration;
        }
        #region OrderDetailList
        public IActionResult OrderDetailList()
        {
            String connectionString = this._configuration.GetConnectionString("myConnectionString");
            SqlConnection connection = new SqlConnection(connectionString);
            connection.Open();
            SqlCommand command = connection.CreateCommand();
            command.CommandType = CommandType.StoredProcedure;
            command.CommandText = "sp_GetAllOrderDetails";
            DataTable dt = new DataTable();
            SqlDataReader reader = command.ExecuteReader();
            dt.Load(reader);
            return View(dt);
        }
        #endregion

        #region DropDown
        public void SetDropDown()
        {
            string connectionString = this._configuration.GetConnectionString("myConnectionString");
            SqlConnection connection = new SqlConnection(connectionString);
            connection.Open();
            SqlCommand command = connection.CreateCommand();
            command.CommandType = CommandType.StoredProcedure;
            command.CommandText = "sp_ProductDropDown";
            SqlDataReader reader = command.ExecuteReader();
            DataTable dt = new DataTable();
            dt.Load(reader);
            List<ProductDropDownModel> productList = new List<ProductDropDownModel>();
            foreach (DataRow product in dt.Rows)
            {
                productList.Add(new ProductDropDownModel { ProductID = Convert.ToInt32(product["ProductID"]), ProductName = product["ProductName"].ToString() });
            }
            command.CommandText = "sp_UserDropDown";
            SqlDataReader reader1 = command.ExecuteReader();
            DataTable dataTable1 = new DataTable();
            dataTable1.Load(reader1);
            List<UserDropDownModel> userList = new List<UserDropDownModel>();
            foreach (DataRow user in dataTable1.Rows)
            {
                userList.Add(new UserDropDownModel() { UserID = Convert.ToInt32(user["UserID"]), UserName = user["UserName"].ToString() });
            }
            command.CommandText = "sp_OrderDropDown";
            SqlDataReader reader2 = command.ExecuteReader();
            DataTable dataTable2 = new DataTable();
            dataTable2.Load(reader2);
            List<OrderDropDownModel> orderList = new List<OrderDropDownModel>();
            foreach (DataRow order in dataTable2.Rows)
            {
                orderList.Add(new OrderDropDownModel() { OrderID = Convert.ToInt32(order["OrderID"]), OrderNumber = order["OrderNumber"].ToString() });
            }
            ViewBag.OrderList = orderList;
            ViewBag.UserList = userList;
            ViewBag.ProductList = productList;
        }
        #endregion

        #region OrderDetailForm
        public IActionResult OrderDetailForm(int? OrderDetailID)
        {
            SetDropDown();
            if(OrderDetailID != null)
            {
                string connectionString = this._configuration.GetConnectionString("myConnectionString");
                SqlConnection connection = new SqlConnection(connectionString);
                connection.Open();
                SqlCommand command = connection.CreateCommand();
                command.CommandType = CommandType.StoredProcedure;
                command.CommandText = "sp_GetOrderDetailByID";
                command.Parameters.AddWithValue("OrderDetailID", OrderDetailID);
                SqlDataReader reader = command.ExecuteReader();
                DataTable dataTable = new DataTable();
                dataTable.Load(reader);
                OrderDetailModel orderDetail = new OrderDetailModel();
                orderDetail.OrderDetailID = Convert.ToInt32(dataTable.Rows[0]["OrderDetailID"]);
                orderDetail.OrderID = Convert.ToInt32(dataTable.Rows[0]["OrderID"]);
                orderDetail.ProductID = Convert.ToInt32(dataTable.Rows[0]["ProductID"]);
                orderDetail.Quantity = Convert.ToInt32(dataTable.Rows[0]["Quantity"]);
                orderDetail.Amount = Convert.ToDecimal(dataTable.Rows[0]["Amount"]);
                orderDetail.TotalAmount = Convert.ToDecimal(dataTable.Rows[0]["TotalAmount"]);
                orderDetail.UserID = Convert.ToInt32(dataTable.Rows[0]["UserID"]);
                connection.Close();
                return View(orderDetail);
            }
            return View();
        }
        #endregion

        #region [HttpPost] OrderDetailForm
        [HttpPost]
        public IActionResult OrderDetailForm(OrderDetailModel odm)
        {
            ModelState.Remove("OrderDetailID");
            ModelState.Remove("TotalAmount");
            if (ModelState.IsValid) {
                string connectionString = this._configuration.GetConnectionString("myConnectionString");
                SqlConnection connection = new SqlConnection(connectionString);
                connection.Open();
                SqlCommand command = connection.CreateCommand();
                command.CommandType = CommandType.StoredProcedure;
                if (odm.OrderDetailID != 0)
                {
                    command.CommandText = "sp_UpdateOrderDetail";
                    command.Parameters.AddWithValue("OrderDetailID", odm.OrderDetailID);
                }
                else
                {
                    command.CommandText = "sp_InsertOrderDetail";
                }
                command.Parameters.AddWithValue("OrderID", odm.OrderID);
                command.Parameters.AddWithValue("ProductID", odm.ProductID);
                command.Parameters.AddWithValue("Quantity", odm.Quantity);
                command.Parameters.AddWithValue("Amount", odm.Amount);
                command.Parameters.AddWithValue("TotalAmount", odm.Quantity*odm.Amount);
                command.Parameters.AddWithValue("UserID", odm.UserID);
                command.ExecuteNonQuery();
                connection.Close();
                ModelState.Clear();
                if (odm.OrderDetailID != 0)
                    return RedirectToAction("OrderDetailList");
                else
                {
                    TempData["SuccessMsg"] = $"<script>alert('{odm.OrderID} OrderDetail Added succesfully');</script>";
                    SetDropDown();
                }
            }
            return View();
        }
        #endregion

        #region OrderDetailDelete
        public IActionResult OrderDetailDelete(int OrderDetailID)
        {
            try
            {
                string connectionString = this._configuration.GetConnectionString("myConnectionString");
                SqlConnection connection = new SqlConnection(connectionString);
                connection.Open();
                SqlCommand command = connection.CreateCommand();
                command.CommandType = CommandType.StoredProcedure;
                command.CommandText = "sp_DeleteOrderDetail";
                command.Parameters.AddWithValue("OrderDetailID", OrderDetailID);
                command.ExecuteNonQuery();
            }
            catch (Exception e)
            {
                TempData["ErrorMessage"] = e.Message;
            }
            return RedirectToAction("OrderDetailList");
        }
        #endregion
    }
}

Views/OrderDetail/OrderDetailForm.cshtml
@model StaticCRUD.Models.OrderDetailModel

<div class="card">
    <div class="card-body">
        <h5 class="card-title">Add Order Detail</h5>

        <!-- Multi Columns Form -->
        <form class="row g-3" asp-controller="OrderDetail" asp-action="OrderDetailForm" method="post">
            @if (Model?.OrderDetailID != null)
            {
                <div class="col-md-6">
                    <label class="form-label" asp-for="OrderDetailID">OrderDetail ID</label>
                    <input type="Text" asp-for="OrderDetailID" value="@Model?.OrderDetailID" class="form-control" disabled>
                    <span asp-validation-for="OrderDetailID" style="color:red"></span>
                </div>
            }
            @Html.HiddenFor(x => x.OrderDetailID)
            <div class="col-md-6">
                <label class="form-label" asp-for="OrderID">Order Number<span class="text-danger">*</span></label>
                <select class="form-select" aria-label="Default Select" asp-for="OrderID" asp-items="@(new SelectList(ViewBag.OrderList, "OrderID","OrderNumber"))">
                    <option disabled selected>Select Order</option>
                </select>
                <span asp-validation-for="OrderID" style="color:red"></span>
            </div>
            <div class="col-md-6">
                <label class="form-label" asp-for="ProductID">Product Name  <span class="text-danger">*</span></label>
                <select class="form-select" aria-label="Default Select" asp-for="ProductID" asp-items="@(new SelectList(ViewBag.ProductList, "ProductID", "ProductName"))">
                    <option disabled selected>Select Product</option>
                </select>
                <span asp-validation-for="ProductID" style="color:red"></span>
            </div>
            <div class="col-md-6">
                <label class="form-label" asp-for="Quantity">Quantity<span class="text-danger">*</span></label>
                <input type="text" asp-for="Quantity" class="form-control">
                <span asp-validation-for="Quantity" style="color:red"></span>
            </div>
            <div class="col-md-6">
                <label class="form-label" asp-for="Amount">Amount<span class="text-danger">*</span></label>
                <input type="text" asp-for="Amount" class="form-control">
                <span asp-validation-for="Amount" style="color:red"></span>
            </div>
            @Html.HiddenFor(x=>x.TotalAmount)
            @* <div class="col-md-6">
                <label class="form-label" asp-for="TotalAmount">Total Amount<span class="text-danger">*</span></label>
                <input type="text" asp-for="TotalAmount" class="form-control">
                <span asp-validation-for="TotalAmount" style="color:red"></span>
            </div> *@
            <div class="col-md-6">
                <label class="form-label" asp-for="UserID">User Name<span class="text-danger">*</span></label>
                <select class="form-select" aria-label="Default Select" asp-for="UserID" asp-items="@(new SelectList(ViewBag.UserList, "UserID", "UserName"))">
                    <option value="" disabled selected>Select User</option>
                </select>
                <span asp-validation-for="UserID" style="color:red"></span>
            </div>
            <div class="col-12">
                <input type="submit" class="btn btn-primary" value="@((Model?.OrderDetailID == null)?"Add":"Update")" />
                <input type="reset" class="btn btn-secondary" value="Reset" @((Model?.OrderDetailID != null) ? "hidden" : "") />
                <a asp-controller="OrderDetail" asp-action="OrderDetailList" class="btn btn-danger">Back</a>
            </div>
        </form><!-- End Multi Columns Form -->
    </div>
</div>
@Html.Raw(TempData["SuccessMsg"])


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/OrderDetail/OrderDetailList.cshtml
@using System.Data;
@model DataTable

<div class="card m-0">
    <div class="card-body">
        <h5 class="card-title">OrderDetail Table</h5>
        @if (TempData["ErrorMessage"] != null)
        {
            <span class="text-danger">@TempData["ErrorMessage"]</span>
            <br>
        }

        <a asp-controller="OrderDetail" asp-action="OrderDetailForm">
            <button type="button" class="btn btn-primary float-end"><i class="ri-add-circle-line"></i> Add Order Detail</button>
        </a>
        <!-- Default Table -->
        <table class="table">
            <thead>
                <tr>
                    @* <th>OrderDetailID</th> *@
                    <th>OrderNumber</th>
                    <th>ProductName</th>
                    <th>Quantity</th>
                    <th>Amount</th>
                    <th>TotalAmount</th>
                    <th>UserName</th>
                    <th scope="col">Actions&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                @foreach (DataRow orderDetail in Model.Rows)
                {
                    <tr>
                        @*<td>@orderDetail["OrderDetailID"]</td>*@
                        <td>@orderDetail["OrderNumber"]</td>
                        <td>@orderDetail["ProductName"]</td>
                        <td>@orderDetail["Quantity"]</td>
                        <td>@orderDetail["Amount"]</td>
                        <td>@orderDetail["TotalAmount"]</td>
                        <td>@orderDetail["UserName"]</td>
                        <td class="d-flex justify-content-evenly">
                            <a method="post" class="btn btn-warning" asp-controller="OrderDetail" asp-action="OrderDetailForm" asp-route-OrderDetailID="@orderDetail["OrderDetailID"]">
                                <i class="bx bxs-edit"></i>
                            </a>
                            <form method="post" asp-controller="OrderDetail" asp-action="OrderDetailDelete">
                                <input type="hidden" name="OrderDetailID" value="@orderDetail["OrderDetailID"]" />
                                <button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete Details of Order : @orderDetail["OrderNumber"]')">
                                    <i class="ri-delete-bin-2-fill"></i>
                                </button>
                            </form>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <!-- End Default Table Example -->
    </div>
</div>