Controllers/BillController.cs
using Microsoft.AspNetCore.Mvc;
using StaticCRUD.Models;
using System.Data.SqlClient;
using System.Data;

namespace StaticCRUD.Controllers
{
    [CheckAccess]
    public class BillController : Controller
    {
        private IConfiguration _configuration;
        public BillController(IConfiguration configuration)
        {
            _configuration = configuration;
        }
        //List<BillModel> bills = new List<BillModel>
        //{
        //    new BillModel { BillID = 1, BillNumber = "BILL001", BillDate = DateTime.Now.AddDays(-1), OrderID = 1, TotalAmount = 200.00m, Discount = 10.00m, NetAmount = 190.00m, UserID = 1 },
        //    new BillModel { BillID = 3, BillNumber = "BILL003", BillDate = DateTime.Now.AddDays(-2), OrderID = 3, TotalAmount = 300.00m, Discount = 20.00m, NetAmount = 280.00m, UserID = 3 },
        //    new BillModel { BillID = 2, BillNumber = "BILL002", BillDate = DateTime.Now, OrderID = 2, TotalAmount = 150.00m, Discount = null, NetAmount = 150.00m, UserID = 2 },
        //};

        #region BillList
        public IActionResult BillList()
        {
            String connectionString = this._configuration.GetConnectionString("myConnectionString");
            SqlConnection connection = new SqlConnection(connectionString);
            connection.Open();
            SqlCommand command = connection.CreateCommand();
            command.CommandType = CommandType.StoredProcedure;
            command.CommandText = "sp_GetAllBills";
            DataTable dt = new DataTable();
            SqlDataReader reader = command.ExecuteReader();
            dt.Load(reader);
            return View(dt);
        }
        #endregion

        #region DropDown
        public void SetDropDown()
        {
            
            string connectionString = this._configuration.GetConnectionString("myConnectionString");
            SqlConnection connection = new SqlConnection(connectionString);
            connection.Open();
            SqlCommand command = connection.CreateCommand();
            command.CommandText = "sp_UserDropDown";
            SqlDataReader reader1 = command.ExecuteReader();
            DataTable dataTable1 = new DataTable();
            dataTable1.Load(reader1);
            List<UserDropDownModel> userList = new List<UserDropDownModel>();
            foreach (DataRow user in dataTable1.Rows)
            {
                userList.Add(new UserDropDownModel() { UserID = Convert.ToInt32(user["UserID"]), UserName = user["UserName"].ToString() });
            }
            command.CommandText = "sp_OrderDropDown";
            SqlDataReader reader2 = command.ExecuteReader();
            DataTable dataTable2 = new DataTable();
            dataTable2.Load(reader2);
            List<OrderDropDownModel> orderList = new List<OrderDropDownModel>();
            foreach (DataRow order in dataTable2.Rows)
            {
                orderList.Add(new OrderDropDownModel() { OrderID = Convert.ToInt32(order["OrderID"]), OrderNumber = order["OrderNumber"].ToString() });
            }
            ViewBag.OrderList = orderList;
            ViewBag.UserList = userList;
        }
        #endregion

        #region BillForm
        public IActionResult BillForm(int? BillID)
        {
            SetDropDown();
            if (BillID != null)
            {
                string connectionString = this._configuration.GetConnectionString("myConnectionString");
                SqlConnection connection = new SqlConnection(connectionString);
                connection.Open();
                SqlCommand command = connection.CreateCommand();
                command.CommandType = System.Data.CommandType.StoredProcedure;
                command.CommandText = "sp_GetBillByID";
                command.Parameters.AddWithValue("BillID", BillID);
                SqlDataReader reader1 = command.ExecuteReader();
                DataTable dataTable1 = new DataTable();
                dataTable1.Load(reader1);
                BillModel billModel = new BillModel();
                billModel.BillID = Convert.ToInt32(dataTable1.Rows[0]["BillID"]);
                billModel.BillNumber = dataTable1.Rows[0]["BillNumber"].ToString();
                billModel.BillDate = Convert.ToDateTime(dataTable1.Rows[0]["BillDate"]);
                billModel.OrderID = Convert.ToInt32(dataTable1.Rows[0]["OrderID"]);
                billModel.TotalAmount = Convert.ToDecimal(dataTable1.Rows[0]["TotalAmount"]);
                billModel.Discount = Convert.ToDecimal(dataTable1.Rows[0]["Discount"]);
                billModel.NetAmount = Convert.ToDecimal(dataTable1.Rows[0]["NetAmount"]);
                billModel.UserID = Convert.ToInt32(dataTable1.Rows[0]["UserID"]);
                connection.Close();
                return View(billModel);
            }
            return View();
        }
        #endregion

        #region [HttpPost] BillForm
        [HttpPost]
        public IActionResult BillForm(BillModel bm)
        {
            ModelState.Remove("BillID");
            ModelState.Remove("NetAmount");
            if (ModelState.IsValid)
            {
                string connectionString = this._configuration.GetConnectionString("myConnectionString");
                SqlConnection connection = new SqlConnection(connectionString);
                connection.Open();
                SqlCommand command = connection.CreateCommand();
                command.CommandType = System.Data.CommandType.StoredProcedure;
                if (bm.BillID != 0)
                {
                    command.CommandText = "sp_UpdateBill";
                    command.Parameters.AddWithValue("BillID", bm.BillID);
                }
                else
                {
                    command.CommandText = "sp_InsertBill";
                }
                command.Parameters.AddWithValue("BillNumber", bm.BillNumber);
                command.Parameters.AddWithValue("BillDate", bm.BillDate);
                command.Parameters.AddWithValue("OrderID", bm.OrderID);
                command.Parameters.AddWithValue("TotalAmount", bm.TotalAmount);
                command.Parameters.AddWithValue("Discount", bm.Discount);
                command.Parameters.AddWithValue("NetAmount", bm.TotalAmount-bm.Discount);
                command.Parameters.AddWithValue("UserID", bm.UserID);
                command.ExecuteNonQuery();
                connection.Close();
                ModelState.Clear();
                if (bm.BillID != 0)
                    return RedirectToAction("BillList");
                else
                {
                    TempData["SuccessMsg"] = $"<script>alert('{bm.BillNumber} Bill Added succesfully');</script>";
                    SetDropDown();
                }
            }
            return View();
        }
        #endregion

        #region Bill Delete
        public IActionResult BillDelete(int BillID)
        {
            try
            {
                string connectionString = this._configuration.GetConnectionString("myConnectionString");
                SqlConnection connection = new SqlConnection(connectionString);
                connection.Open();
                SqlCommand command = connection.CreateCommand();
                command.CommandType = CommandType.StoredProcedure;
                command.CommandText = "sp_DeleteBill";
                command.Parameters.AddWithValue("BillID", BillID);
                command.ExecuteNonQuery();
            }
            catch (Exception e)
            {
                TempData["ErrorMessage"] = e.Message;
            }
            return RedirectToAction("BillList");
        }
        #endregion
    }
}

Views/Bill/BillForm.cshtml
@model StaticCRUD.Models.BillModel

<div class="card">
    <div class="card-body">
        <h5 class="card-title">Add Bill</h5>

        <!-- Multi Columns Form -->
        <form class="row g-3" asp-controller="Bill" asp-action="BillForm" method="post">
            @if (Model?.BillID != null)
            {
                <div class="col-md-6">
                    <label class="form-label" asp-for="BillID">Bill ID</label>
                    <input type="Text" asp-for="BillID" value="@Model?.BillID" class="form-control" disabled>
                    <span asp-validation-for="BillID" style="color:red"></span>
                </div>
            }
            @Html.HiddenFor(x=>x.BillID)
            <div class="col-md-6">
                <label class="form-label" asp-for="BillNumber">Bill Number<span class="text-danger">*</span></label>
                <input type="text" asp-for="BillNumber" class="form-control">
                <span asp-validation-for="BillNumber" style="color:red"></span>
            </div>
            <div class="col-md-6">
                <label class="form-label" asp-for="BillDate">Bill Date<span class="text-danger">*</span></label>
                <input type="datetime-local" asp-for="BillDate" class="form-control">
                <span asp-validation-for="BillDate" style="color:red"></span>
            </div>
            <div class="col-md-6">
                <label class="form-label" asp-for="OrderID">Order Number<span class="text-danger">*</span></label>
                <select class="form-select" aria-label="Default Select" asp-for="OrderID" asp-items="@(new SelectList(ViewBag.OrderList, "OrderID", "OrderNumber"))">
                    <option value="" disabled selected>Select Order</option>
                </select>
                <span asp-validation-for="OrderID" style="color:red"></span>
            </div>
            <div class="col-md-6">
                <label class="form-label" asp-for="TotalAmount">Total Amount<span class="text-danger">*</span></label>
                <input type="text" asp-for="TotalAmount" class="form-control">
                <span asp-validation-for="TotalAmount" style="color:red"></span>
            </div>
            <div class="col-md-6">
                <label class="form-label" asp-for="Discount">Discount<span class="text-danger">*</span></label>
                <input type="text" asp-for="Discount" class="form-control">
                <span asp-validation-for="Discount" style="color:red"></span>
            </div>
            @Html.HiddenFor(x=>x.NetAmount)
            @* <div class="col-md-6">
                <label class="form-label" asp-for="NetAmount">Net Amount<span class="text-danger">*</span></label>
                <input type="text" asp-for="NetAmount" class="form-control" value="0.0">
                <span asp-validation-for="NetAmount" style="color:red"></span>
            </div> *@
            <div class="col-md-6">
                <label class="form-label" asp-for="UserID">User Name<span class="text-danger">*</span></label>
                <select class="form-select" aria-label="Default Select" asp-for="UserID" asp-items="@(new SelectList(ViewBag.UserList, "UserID", "UserName"))">
                    <option value="" disabled selected>Select User</option>
                </select>
                <span asp-validation-for="UserID" style="color:red"></span>
            </div>
            <div class="col-12">
                <input type="submit" class="btn btn-primary" value="@((Model?.BillID == null)?"Add":"Update")" />
                <input type="reset" class="btn btn-secondary" value="Reset" @((Model?.BillID != null) ? "hidden" : "") />
                <a asp-controller="Bill" asp-action="BillList" class="btn btn-danger">Back</a>
            </div>
        </form><!-- End Multi Columns Form -->
    </div>
</div>
@Html.Raw(TempData["SuccessMsg"])

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Bill/BillList.cshtml
@using System.Data;
@model DataTable;

<div class="card m-0">
    <div class="card-body">
        <h5 class="card-title">Bill Table</h5>
        @if (TempData["ErrorMessage"] != null)
        {
            <span class="text-danger">@TempData["ErrorMessage"]</span>
            <br>
        }

        <a asp-controller="Bill" asp-action="BillForm">
        <button type="button" class="btn btn-primary float-end"><i class="ri-add-circle-line"></i> Add Bill</button>
        </a>
        <!-- Default Table -->
        <table class="table">
            <thead>
                <tr>
                    @* <th>BillID</th> *@
                    <th>BillNumber</th>
                    <th>BillDate</th>
                    <th>OrderNumber</th>
                    <th>TotalAmount</th>
                    <th>Discount</th>
                    <th>NetAmount</th>
                    <th>UserName</th>
                    <th scope="col">Actions&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                @{
                    foreach (DataRow bill in Model.Rows)
                    {
                        <tr>
                            @*<td>@bill["BillID"]</td>*@
                            <td>@bill["BillNumber"]</td>
                            <td>@bill["BillDate"]</td>
                            <td>@bill["OrderNumber"]</td>
                            <td>@bill["TotalAmount"]</td>
                            <td>@bill["Discount"]</td>
                            <td>@bill["NetAmount"]</td>
                            <td>@bill["UserName"]</td>
                            <td class="d-flex justify-content-evenly">
                                <a method="post" class="btn btn-warning" asp-controller="Bill" asp-action="BillForm" asp-route-BillID="@bill["BillID"]">
                                    <i class="bx bxs-edit"></i>
                                </a>
                                <form method="post" asp-controller="Bill" asp-action="BillDelete">
                                    <input type="hidden" name="BillID" value="@bill["BillID"]" />
                                    <button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete Bill : @bill["BillNumber"]')">
                                        <i class="ri-delete-bin-2-fill"></i>
                                    </button>
                                </form>
                            </td>
                        </tr>
                    }
                }
            </tbody>
        </table>
        <!-- End Default Table Example -->
    </div>
</div>